# Generated by Django 5.0.7 on 2024-07-14 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Food', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=255)),
                ('p_desc', models.TextField()),
                ('p_img', models.ImageField(default='img/products/OliveOil.jpg', upload_to='img/products/')),
                ('p_likes', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producers.producer')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['p_name'],
            },
        ),
    ]
