# Generated by Django 5.0.7 on 2024-07-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='Greek Producer', max_length=150)),
                ('desc', models.TextField(default='Greek Product')),
                ('epost', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('producer_logo', models.ImageField(default='/img/producers/olive_branch.jpg', upload_to='img/producers/')),
            ],
            options={
                'verbose_name_plural': 'Producers',
            },
        ),
    ]
