# Generated by Django 5.0.7 on 2024-07-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_desc', models.TextField()),
                ('vendor_img', models.ImageField(default=None, upload_to='img/vendors/')),
            ],
            options={
                'verbose_name_plural': 'Vendors',
                'ordering': ['vendor_name'],
            },
        ),
    ]
